version: "3.9"
services:
  api:
    build:
      ./api
    ports:
    - 8001:80
    volumes:
    - ./api/todo-api:/var/www
  frontend:
    build:
      ./frontend
    ports:
    - 8000:80
    volumes:
    - ./frontend:/usr/share/nginx/html
  mysql:
    image: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass